language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - libstdc++-5-dev  # default version is not valgrind-clean

before_install:
  - CXX=clang++

script:
  - ./test_layers 000 070
  - ./test_layers 070 999
  - ./test_layers chessboard
  - ./test_layers edit

notifications:
  email:
    on_success: never
    on_failure: always
