language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - libstdc++-5-dev  # default version is not valgrind-clean

before_install:
  - CXX=clang++

# test_layers takes a long time; divide up the work into multiple jobs on the
# matrix so we don't time out on Travis
matrix:
  include:
    - env: CXX=clang++ START=000 END=020
    - env: CXX=clang++ START=020 END=040
    - env: CXX=clang++ START=040 END=060
    - env: CXX=clang++ START=060 END=070
    - env: CXX=clang++ START=070 END=080
    - env: CXX=clang++ START=080 END=090
    - env: CXX=clang++ START=090 END=999
    - env: CXX=clang++ START=chessboard
    - env: CXX=clang++ START=edit

script:
  - ./test_layers $START $END

notifications:
  email:
    on_success: never
    on_failure: always
