language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - libstdc++-5-dev  # default version is not valgrind-clean

before_install:
  - CXX=clang++

matrix:
  include:
    - env: CXX=clang++ START=000 END=070
    - env: CXX=clang++ START=070 END=999
    - env: CXX=clang++ START=chessboard
    - env: CXX=clang++ START=edit

script:
  - ./test_layers $START $END

notifications:
  email:
    on_success: never
    on_failure: always
