language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - libstdc++-5-dev  # default version is not valgrind-clean

before_install:
  - CXX=clang++

# test_layers takes a long time; divide up the work into multiple jobs on the
# matrix so we don't time out on Travis
matrix:
  include:
    - env: CXX=clang++ START=000 END=040
    - env: CXX=clang++ START=040 END=055
    - env: CXX=clang++ START=055 END=060
    - env: CXX=clang++ START=060 END=065
    - env: CXX=clang++ START=065 END=070
    - env: CXX=clang++ START=070 END=075
    - env: CXX=clang++ START=075 END=080
    - env: CXX=clang++ START=080 END=085
    - env: CXX=clang++ START=085 END=090
    - env: CXX=clang++ START=090 END=999
    - env: CXX=clang++ START=chessboard
    - env: CXX=clang++ START=edit
    - env: CXX=clang++ START=edit2
    - env: CXX=clang++ START=edit3
    - env: CXX=clang++ START=edit4

script:
  - ./test_layers $START $END

notifications:
  email:
    on_success: never
    on_failure: always
